// <auto-generated />
namespace Journalx3Piska.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class InitialTrigger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialTrigger));
        
        string IMigrationMetadata.Id
        {
            get { return "202605041318542_InitialTrigger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
