// <auto-generated />
namespace Journalx3Piska.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class MakeAverageGradeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeAverageGradeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202605062343530_MakeAverageGradeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
